/*
Copyright (c) 2018, 2019, 2020 Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */

#include <stdint.h>

#if defined(__x86_64__)
#include <arch/x86_64/cpuio.h>
#include <arch/x86_64/cpufuncs.h>
#endif


#include <feral/feralstatus.h>
#include <feral/stdtypes.h>
#include <feral/handle.h>
#include <feral/kern/frlos.h>
#include <mm/mm.h>

#include <feral/kern/krnlfuncs.h>
#include <feral/kern/krnlbase.h>

#include <krnl.h>
#include <kern_ver.h>

#include <arch/processor.h>

static UINT8 FeralVersionMajor;
static UINT8 FeralVersionMinor;
static UINT8 FeralVersionPatch;

/* 
	Things to do in order:
	Keyboard input [on this, getting close to working..?]
	In-memory filesystem
	On-disk filesystem (ext2 is enough, 8.3 FAT would be OK to also support)
	Get user mode working!
	Working libc
	System call mechanism. Write a "native" driver (program under env,
	the kernel passes off to the appropriate function for the driver. Kernel
	itself only throws syscall work at drivers to do.)
	We'll eventually need Linux emulation for a "port" of LLVM/Clang, NASM,
	etc., without actually modifying the binary. (Should be unmodified.)
	We'll also want to port a JVM, golang, Python (either 2 or 3), and
	some other stuff too, just for fun.
	
	Work on being self-hosting: Feral needs to compile on Feral.
	We'll also want to create (or port) a nice desktop windowing protocol
	like X, Wayland, or just make a nice one that's specific to Waypoint.
	Likewise, we'll need to figure out how to get some NIC drivers onboard.
	Get rid of multiboot 2 stuff, eventually make our own EFI bootloader.
	Write a new filesystem focusing on getting as good read speeds as
	possible on modern SSDs. At this stage, we'll want support for AHCI,
	SATA, and NVMe. Do not care about IDE/PATA.
	Write a hypervisor, and embed it in the kernel! (This will be fun!)
	Graphics drivers are pretty important to get working.
	
	Nothing older than the vega10 should be supported. There's really no
	need to: I don't have a lot of GPUs lying around, and since
	I'm really only focusing on the hardware I've got, I don't really
	have a reason to support older GPUs, especially from a different vendor.
	(Though, getting Blue GPUs to work sounds fun.)
	
	Getting version control on a Feral system would be great!
	Dogfood, dogfood, and dogfood more. If you don't dogfood, then
	you're not going to be as willing to fix it.
	
	Get a web browser going. Write a LibHTML, possibly port an open
	source ES6 engine like ChakraCore? Build one
	from scratch? At least have HTML4 support, and pretend HTML5 + CSS.
	Also, consider porting Mono.
*/

/* TODO */
#if defined(__aarch64__)
FERALSTATUS KiPrintLine()
{
}

FERALSTATUS KiPrintWarnLine()
{
}
#endif

/* 	
	This is the kernel's *real* entry point. 
	TODO: some mechanism for a Feral-specific bootloader to skip the 
	multiboot stuff and just load this.
*/
VOID KiSystemStartup(KrnlEnvironmentBlock *EnvBlock)
{
	/* First off, ensure we load all the drivers, 
	 * so we know what's going on. Use a couple prints to check for
	 * any regressions. 
	 */
	KiUpdateFirmwareFunctions(EnvBlock->FunctionTable, EnvBlock->CharMap);

	FeralVersionMajor = FERAL_VERSION_MAJOR;
	FeralVersionMinor = FERAL_VERSION_MINOR;
	FeralVersionPatch = FERAL_VERSION_PATCH;

	KiPrintFmt("\nStarting Feral Kernel \"%s\" Version %01u.%01u.%01u\n",
		FERAL_VERSION_SHORT,
		FERAL_VERSION_MAJOR,
		FERAL_VERSION_MINOR,
		FERAL_VERSION_PATCH);

	KiPrintLine("Copyright (c) 2018-2019, Brian Schnepp");
	KiPrintLine("Licensed under the Boost Software License.");
	KiPrintFmt("Booted using %s\n",
		EnvBlock->FunctionTable->GetFirmwareName());
	KiPrintFmt("%s\n", "Preparing execution environment...");

	KiStartupSystem(FERAL_SUBSYSTEM_ARCH_SPECIFIC);
	KiStartupSystem(FERAL_SUBSYSTEM_MEMORY_MANAGEMENT);

	/* Only load drivers *after* base system initializtion. */
	KiPrintFmt("Loading all drivers...\n");
	FERALSTATUS KiLoadAllDrivers(VOID);

	/* These are macroed away at release builds.  
	 * They're eliminated at build time.
	 */
	KiDebugPrint("INIT Reached here.");
	/* 
		TODO: Call up KiStartupProcessor for each processor.
		Each processor should have it's x87 enabled, so we can do SSE 
		stuff in usermode. 
	 */
}

/* UINT64 just in case there's some crazy 6 billion core server one day. */
VOID KiStartupProcessor(UINT64 ProcessorNumber)
{
	/*  Create a new stack for this core. */
}



FERALSTATUS KeBootstrapSystem(VOID)
{
	/* Bootstrap process to actually get to user mode. */
	return STATUS_SUCCESS;
}



/*
 * Some things aren't set up by the firmware for us, or known
 * to be.
 * So, deal with that.
 */
VOID KiStartupMachineDependent(VOID)
{
#if defined(__x86_64__) || defined(__i386__)
	/* Be careful: '__riscv__' is deprecated. */
	x86InitializeIDT();
#elif defined(__riscv)

#elif defined(__aarch64__)

#endif
}
