/*
Copyright (c) 2019, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */

#ifndef _FERAL_HEAP_H_
#define _FERAL_HEAP_H_

/* 128 is a size just right where you're better off on stack if smaller */
#define ALLOC_BLOCK_SIZE_MINIMUM (128)
 
typedef struct Node
{
	BOOL Dirty;
	BOOL Used;
	VOID *Area;
}Node;

/* 
	A thread holds an arena where memory could
	be allocated or freed from.
	
	A lock is in place such that if n(thread) > n(cores),
	then the portion of the kernel waiting on it can be halted
	until the current operation is done.
 */
typedef struct Arena
{
	UINT8 Lock;
	UINT64 ThreadIndex;
	UINT64 Size;
	VOID *Area;
	Node *Root;
}Arena;


#endif
