/*
Copyright (c) 2018, 2019, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining  a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */


/* We try to hide things behind a simple typedef in case the API changes.
   Thus, we maintain comatibility, even between any releases, and avoid 
   compatibility hacks.
 */

#ifndef _FERAL_HANDLE_H_
#define _FERAL_HANDLE_H_

#include <feral/stdtypes.h>
#include <feral/port/port.h>

typedef enum HANDLETYPE
{
	HANDLE_TO_HANDLE,		
	HANDLE_TO_INSTANCE,		
	HANDLE_TO_RMS_KEY,		
	HANDLE_TO_FILE,		
	HANDLE_TO_RESOURCE,		
	HANDLE_TO_TASK,		
	HANDLE_TO_PROCESS,		
	HANDLE_TO_THREAD,		
	HANDLE_TO_ACCESS_RIGHTS,	
	HANDLE_TO_EVENT,		
	HANDLE_TO_SEMAPHORE,		
	HANDLE_TO_MUTEX,		
	HANDLE_TO_TIMER,		
	HANDLE_TO_DESKTOP,		
	HANDLE_TO_FRAME,		
	HANDLE_TO_LIBRARY,		
	HANDLE_TO_LINK,		
}HANDLETYPE;


/* All handles just subclass this. */
typedef struct HANDLE
{
	HANDLETYPE Type;
	FERALPORT Port;
	UINT64 Size;
}HANDLE;


struct HHANDLE;
struct HINSTANCE;
struct HKEY;
struct HFILE;

struct HMUTEX;

/* Compatibility with badly ported programs. */
typedef struct HMUTEX HMUTANT;


#endif
