/*
Copyright (c) 2019, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */

#include <feral/stdtypes.h>

#ifndef _FERAL_MEMORY_H_
#define _FERAL_MEMORY_H_


/* 
 	TODO: Try to mitigate Rowhammer as best we can. 
 	All dynamic memory should *never* be contiguous in memory
 	as compared to it's normal memory model (ie, array > 1 page is
 	not in right order on physical memory.), but take care to ensure
 	other applications don't get a slice of memory between another
 	program's pages.
 	
 	We'll *eventually* be unable to deal with this, but we can do something
 	like arbitrarilly say that programs run under users without a specific
 	privilege can only use up to a specific, non-100% amount of total
 	available memory (memory quotas), something like 10% for "we want to
 	be as hard to break as possible" up to 75% for "don't care about security" types.
 	
 	Then, it's up to users to set up program permissions correctly, set up security policies,
 	and don't try to create a 'root' user.
 */



#endif
