/*
Copyright (c) 2018, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */

#ifndef _FERAL_DEVICES_GPU_H_
#define _FERAL_DEVICES_GPU_H_

// I won't be writing the Polaris drivers (someone else should). They are in here for compatibility for a GPU not that old. (I did say "from 2017 onwards", after all.)
typedef enum amdgpu_family
{
	CHIP_POLARIS10,
	CHIP_POLARIS11,
	CHIP_POLARIS12,
	CHIP_POLARIS20,
	
	CHIP_VEGA10,
	CHIP_VEGARAVEN,

	GHIP_NAVI,
	CHIP_LAST,
}amdgpu_family;


typedef enum nvgpu_family
{
	/* 700-series (Kepler refined)*/
	CHIP_GM107,
	CHIP_GK104,
	CHIP_GK110,

	/* 900-series (Maxwell) */
	CHIP_GM206,
	CHIP_GM204,
	CHIP_GM200,

	/* 1000-series (Pascal) */
	// TODO
}nvgpu_family;
#endif
