/*
Copyright (c) 2018, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining  a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */
 
 #ifndef _FERAL_GPU_CLUSTER_H_
 #define _FERAL_GPU_CLUSTER_H_
 
 #include <feral/string.h>
 
 /* organize a couple GPUs as a cluster, exposing themselves as a single graphics card to various graphics APIs. */
 /* For example, we could have 2 Polaris 550s in one machine, a 1050 Ti in another, and some iGPU in the local machine, and Feral schedules them
  	accordingly, such that we can so multi-GPU rendering at the cost of network latency. (for example, the iGPU could do just 2D text, the 1050 Ti does shading, and the dual 550s do geometry and whatnot.
  */
 typedef struct GPUCluster
{
	FERALSTRING ClusterName;
	/* TODO */
}GPUCluster;
 
 
 #endif
