/*
Copyright (c) 2020 Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */

#include <feral/stdtypes.h>
#include <stdint.h>

#if defined(__x86_64__)
#include <arch/x86_64/cpuio.h>
#include <arch/x86_64/cpufuncs.h>
#endif


#include <feral/feralstatus.h>
#include <feral/stdtypes.h>
#include <feral/handle.h>
#include <feral/kern/frlos.h>
#include <mm/mm.h>

#include <feral/kern/krnlfuncs.h>
#include <feral/kern/krnlbase.h>

#include <krnl.h>
#include <kern_ver.h>

#include <arch/processor.h>


#if defined(FERAL_BUILD_STANDALONE_UEFI_)

#include <libreefi/efi.h>
#include <feral/kern/krnlentry.h>

static KrnlFirmwareFunctions FirmwareFuncs = {0};
static KrnlCharMap CharMap = {0};
static KrnlEnvironmentBlock EnvBlock = {0};

#include "charmap_default.inl"


FERALSTATUS KiStartupSystem(KiSubsystemIdentifier Subsystem)
{
	if (Subsystem == FERAL_SUBSYSTEM_MEMORY_MANAGEMENT)
	{
	}
	else if (Subsystem == FERAL_SUBSYSTEM_ARCH_SPECIFIC)
	{
	}
	else
	{
		/*  Placeholder for more stuff later on. (disks, network...) */
	}
}

STRING GetEfiFirmwareClaim()
{
	return "UEFI 2.8 compatible firmware";
}


VOID kern_init(EfiBootInfo *BootInfo)
{
	/*  Issue is now the framebuffers aren't mapped in memory. 
	 *  We'll need to put the EFI stuff somewhere in the first 2MB,
	 *  so the kernel can read that data.
	 *  (BootInfo right now is wherever EFI feels like it...)
	 */

	UINT32 *FramebufferTemp = (UINT32 *)(BootInfo->FramebufferPAddrs[2]);
	for (int i = 0; i < (BootInfo->FramebufferPAddrs[1]); ++i)
	{
		for (int k = 0; k < (BootInfo->FramebufferPAddrs[0]); ++k)
		{
			UINT32 FBVal = 0xFFFFFFFF;
			//FramebufferTemp[i] = FBVal;
		}
	}


	/* Set up the character map. */
	CharMap.CharMapWidth = 8;
	CharMap.CharMapHeight = 8;

	CharMap.NumNumerals = 10;
	CharMap.NumLowerCase = 26;
	CharMap.NumUpperCase = 26;
	CharMap.CharMap = DefaultCharMap;

	FirmwareFuncs.GetFirmwareName = GetEfiFirmwareClaim;

	EnvBlock.CharMap = &CharMap;
	EnvBlock.FunctionTable = &FirmwareFuncs;

	//KiSystemStartup(&EnvBlock);
	for (;;){} /* Prevent leaving this function for whatever reason. */
}



#endif
