/*
Copyright (c) 2019, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */
 
#include <feral/feralstatus.h>
#include <feral/stdtypes.h>

#include <mm/mm.h>
#include <mm/page.h>

#if defined(__x86_64__) || defined(__i386__)
/* TODO: Deal with 32-bit x86 not supporting everything. Maybe force PAE? */
#include <arch/x86_64/mm/pageflags.h>
#endif


/*
	Let's totally overhaul this.
	
	The lowest level is the physical memory manager.
	We get the ranges from the init process,
	which creates a structure holding valid physical ranges.
	
	The virtual memory manager handles the mapping somehow to
	virtual addresses? 
	
	**then** we use kmalloc().
	
	(in other words, stop mashing everything together because it's making
	an incoherent mess.)
*/

typedef struct MemoryManagementState
{
	/* For now, we *do not* support huge pages generally. */
	MmPhysicalAllocationInfo *pAllocInfo;
	
	/* Sum up total free area, right bitshift 3. */
	UINT8 *BitmaskUsedFrames;
	
	/* NOTE: We need to check if the frame goes beyond
	   the first range. If it did, then we need to move
	   on to the next one. Keep going for each range
	   we've got.
	   
	   Each bit represents free or in use. 0 for free,
	   1 for in use.
	 */
}MemoryManagementState;

/* Not the best thing ever, but... */
static MemoryManagementState MmState;


/* TODO: Move to other source file. */
FERALSTATUS KiInitializeMemMgr(MmCreateInfo *info)
{
	MmState.pAllocInfo = info->pPhysicalAllocationInfo;
	
	UINT64 FreeMemory = 0;
	UINT_PTR MemSz = 0;
	MmFreeAreaRange AreaToPlaceBuffer = {0};
	for (UINT64 n = 0; n < MmState.pAllocInfo->FreeAreaRangeCount; ++n)
	{
		MmFreeAreaRange range = MmState.pAllocInfo->Ranges[n];
		if (range.sType != MM_STRUCTURE_TYPE_FREE_AREA_RANGE)
		{
			KiStopError(STATUS_MEMORY_ACCESS_VIOLATION);
		}
		/* HACK: Don't do it in the small area below 1MB. */
		if (MemSz == 0 && range.Size > 1024 * 1024)
		{
			MemSz = range.Size;
			AreaToPlaceBuffer = range;
		}
		FreeMemory += (UINT64)range.Size;
	}
	
	KiPrintFmt("Registered free memory: %uMB\n", FreeMemory / (1024 * 1024));
	
	/* Shift over based on the size of pages being used. */
	UINT64 sz = MmState.pAllocInfo->FrameSize;
	UINT8 ShiftAmt = 3;	/* Map 1 bit to 8 bytes at least (2^3) */
	while (sz >>= 1)
	{ 
		++ShiftAmt;
	}
	
	FreeMemory >>= ShiftAmt;
	
	/* We don't have a malloc yet.*/
	UINT8 *map = (UINT8*)AreaToPlaceBuffer.Start;
	MmState.BitmaskUsedFrames = map;
	UINT_PTR MaxArea = map;
	/* Mark this area as in use. */
	for (UINT64 part = 0; part <= AreaToPlaceBuffer.Start / MmState.pAllocInfo->FrameSize; ++part)
	{
		SetMemoryAlreadyInUse(AreaToPlaceBuffer.Start + (MmState.pAllocInfo->FrameSize * part), TRUE);
	} 
	return STATUS_SUCCESS;
}

FERALSTATUS GetMemoryAlreadyInUse(UINT_PTR Location, BOOL *Status)
{
	/* Get the containing frame. */
	UINT64 sz = MmState.pAllocInfo->FrameSize;
	UINT8 ShiftAmt = 3;	/* Map 1 bit to 8 bytes at least (2^3) */
	while (sz >>= 1)
	{ 
		++ShiftAmt;
	}
	UINT64 Loc = (Location >> ShiftAmt);
	
	/* Check if this is out of range... */
	UINT_PTR maxRange = 0;
	for (UINT64 i = 0; i < MmState.pAllocInfo->FreeAreaRangeCount; ++i)
	{
		UINT_PTR curEnd = MmState.pAllocInfo->Ranges[i].End; 
		if (curEnd > maxRange)
		{
			maxRange = curEnd;
		}
	}
	if (Location > maxRange)
	{
		*Status = FALSE;
		return STATUS_INVALID_MEMORY_LOCATION;
	}
	
	/* Now let's look at our PMM bitmap. */
	UINT8 ContainingByte = MmState.BitmaskUsedFrames[Loc];
	
	/* Think this is right? */
	UINT8 BitNum = (Loc << 3) % 8;
	UINT8 BitStatus = (ContainingByte >> BitNum) & 0x01;
	*Status = BitStatus;
	return STATUS_SUCCESS;
}

FERALSTATUS SetMemoryAlreadyInUse(UINT_PTR Location, BOOL Status)
{

	/* Get the containing frame. */
	UINT64 sz = MmState.pAllocInfo->FrameSize;
	UINT8 ShiftAmt = 3;	/* Map 1 bit to 8 bytes at least (2^3) */
	while (sz >>= 1)
	{ 
		++ShiftAmt;
	}
	UINT64 Loc = (Location >> ShiftAmt);
	
	/* Check if this is out of range... */
	UINT_PTR maxRange = 0;
	for (UINT64 i = 0; i < MmState.pAllocInfo->FreeAreaRangeCount; ++i)
	{
		UINT_PTR curEnd = MmState.pAllocInfo->Ranges[i].End; 
		if (curEnd > maxRange)
		{
			maxRange = curEnd;
		}
	}
	if (Location > maxRange)
	{
		return STATUS_INVALID_MEMORY_LOCATION;
	}
	
	
	/* Now let's look at our PMM bitmap. */
	UINT8 ContainingByte = MmState.BitmaskUsedFrames[Loc];
	
	/* Think this is right? */
	UINT8 BitNum = (Loc << 3) % 8;
	UINT8 InUse = ContainingByte >> BitNum;

	if (InUse && !Status)
	{
		/* Free it */
		MmState.BitmaskUsedFrames[Loc] = (ContainingByte) & ((255) ^ (1 << BitNum));
		return STATUS_SUCCESS;
	} else if (!InUse && Status) {
		/* Allocate it. */
		MmState.BitmaskUsedFrames[Loc] = (ContainingByte) | (1 << BitNum);
		return STATUS_SUCCESS;
	} else {
		return STATUS_MEMORY_ACCESS_VIOLATION;
	}
	
	
}
