/*
Copyright (c) 2018, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */

#include <feral/stdtypes.h>
#include <feral/kern/frlos.h>
#include <feral/kern/ki.h>

#include "sec.h"

#if defined(__x86_64__)
#include <arch/x86_64/vga/vga.h>
#endif

FERALSTATUS KiStopError(IN FERALSTATUS Status)
{
#if defined(__x86_64__)
	KiBlankVgaScreen(25, 80, VGA_BLUE);
	char* errorMsg = "A problem has been detected and Feral has shutdown to prevent further damage.";
	UINTN length = 0;
	KiGetStringLength(errorMsg, &length);
	VgaPrintln(VGA_WHITE, VGA_BLUE, errorMsg, length);
	
	KiPrintLine("");
	return STATUS_ERROR;
	/* Todo: be more useful for error checking */
#endif
}

__attribute__((noreturn))
VOID __stack_chk_fail(void)
{
	/* This is _horribly_ primitive, but for now, good enough. */
	KiStopError(STATUS_INVALID_MEMORY_LOCATION);
}
