/*
Copyright (c) 2018, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization
obtaining  a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute, execute,
and transmit the Software, and to prepare derivative works of the Software,
and to permit third-parties to whom the Software is furnished to do so, all
subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer, must
be included in all copies of the Software, in whole or in part, and all
derivative works of the Software, unless such copies or derivative works are
solely in the form of machine-executable object code generated by a source
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.
 */


#include <feral/stdtypes.h>
#include <ddk/frlddk.h>
#include <ddk/interface.h>

#if defined(__x86_64__) || defined(__i386__)
#include <arch/x86_64/cpuio.h>
#endif

#define COM1_PORT 0x3FB
#define COM1_DATA (COM1_PORT)

#define SERIAL_FIFO_COMMAND(port)  (port + 2)
#define SERIAL_LINE_COMMAND(port)  (port + 3)
#define SERIAL_MODEM_COMMAND(port) (port + 4)
#define SERIAL_LINE_STATUS(port)   (port + 5)

#define SERIAL_LINE_ENABLE_DLAB (0x80)

VOID SerialConfigureBaudRate(UINT16 Port, UINT16 Divisor)
{
#if defined(__x86_64__) || defined(__i386__)
	x86outb(SERIAL_LINE_COMMAND(Port), SERIAL_LINE_ENABLE_DLAB);
	x86outb(Port, (Divisor >> 8) & 0x00FF);
	x86outb(Port, (Divisor >> 0) & 0x00FF);
#endif
}


VOID SerialTransmitCharacter(UINT16 Port, CHAR c)
{
#if defined(__x86_64__) || defined(__i386__)
	if ((x86inb(SERIAL_LINE_STATUS(Port)) & (1 << 5)) == 0)
	{
		x86outb(Port, c);
	}
#endif
}

FERALSTATUS FrlDriverMain(VOID)
{
	//FERAL_DRIVER SerialDriver = {0};
	return STATUS_SUCCESS;
}
