/*
Copyright (c) 2020, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute, execute,
and transmit the Software, and to prepare derivative works of the Software,
and to permit third-parties to whom the Software is furnished to do so, all
subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer, must
be included in all copies of the Software, in whole or in part, and all
derivative works of the Software, unless such copies or derivative works are
solely in the form of machine-executable object code generated by a source
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.
 */

#include <feral/stdtypes.h>
#include <feral/feralstatus.h>

#include <feral/kern/krnlbinfuncs.h>

/**
 * @brief Takes the logarithm of the absolute value of a number by the base 2.
 * That is, 2 can be multiplied by itself by the number returned in Result, 
 * and the resulting number from that will be the nearest power of two, rounding
 * downwards from the original number. As such, KiLog2Int(-4096) will have the
 * same result as KiLog2Int(8000)
 * 
 * @author Brian Schnepp
 * @param Input The input number, as an signed 64-bit integer
 * @param Result A pointer to the result of this operation
 * 
 */
FERALSTATUS FERALAPI KiLog2Int(IN INT64 Input, OUT INT64 *Result)
{
	INT64 ResultOne;
	INT64 ResultTwo;

	/* Attempt both, then return the correct one. */
	KiLog2UInt((UINT64)(Input), &ResultOne);
	KiLog2UInt((UINT64)(-Input), &ResultOne);

	/* And use branchless programming to pick between them. */
	(*Result) = ((Input <= 0) * (ResultTwo)) + ((Input > 0) * (ResultOne));
	return STATUS_SUCCESS;
}

/**
 * @brief Takes the logarithm of a given number by the base 2.
 * That is, 2 can be multiplied by itself by the number returned in Result, 
 * and the resulting number from that will be the nearest power of two, rounding
 * downwards from the original number. As such, KiLog2UInt(4096) will have the
 * same result as KiLog2UInt(8000)
 * 
 * @author Brian Schnepp
 * @param Input The input number, as an unsigned 64-bit integer
 * @param Result A pointer to the result of this operation
 * 
 */
FERALSTATUS FERALAPI KiLog2UInt(IN UINT64 Input, OUT INT64 *Result)
{
	INT64 Res = 0;

	/* Terribly slow. */
	UINT64 Copy = Input;
	while (Copy >= 2)
	{
		Res++;
		Copy /= 2;
	}

	(*Result) = Res;
	return STATUS_SUCCESS;
}