/*
Copyright (c) 2020, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization
obtaining  a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute, execute,
and transmit the Software, and to prepare derivative works of the Software,
and to permit third-parties to whom the Software is furnished to do so, all
subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer, must
be included in all copies of the Software, in whole or in part, and all
derivative works of the Software, unless such copies or derivative works are
solely in the form of machine-executable object code generated by a source
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.
 */

#include <feral/stdtypes.h>

#if defined(__x86_64__)
#include <arch/x86_64/cpuinfo.h>
#endif

#ifndef _FERAL_KRNL_PROCESSOR_H_
#define _FERAL_KRNL_PROCESSOR_H_

struct KiPrivateProcessorInfo;

typedef enum KeProcessorFamily
{
	KERNEL_PROCESSOR_FAMILY_INVALID = 0,
	KERNEL_PROCESSOR_FAMILY_X86_64,
	KERNEL_PROCESSOR_FAMILY_AARCH64,
	KERNEL_PROCESSOR_FAMILY_RV64GCH,
	KERNEL_PROCESSOR_FAMILY_OPENPOWER,
	KERNEL_PROCESSOR_FAMILY_XEN_X86_64, /* Maybe one day? */
} KeProcessorFamily;

typedef struct KiProcessorInfo
{
	KeProcessorFamily CpuType;
	CHAR *ProcessorVendor;
	CHAR *ProcessorName;

	UINT32 PhysCores;
	UINT32 VirtCores; /* whatever your branding of SMT is. */

	UINT32 CPUStepping; /* In case we need to check for F00F or something.*/

	struct KiPrivateProcessorInfo PrivateInfo;
} KiProcessorInfo;

#endif