/*
Copyright (c) 2019, 2020, 2021, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute, execute,
and transmit the Software, and to prepare derivative works of the Software,
and to permit third-parties to whom the Software is furnished to do so, all
subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer, must
be included in all copies of the Software, in whole or in part, and all
derivative works of the Software, unless such copies or derivative works are
solely in the form of machine-executable object code generated by a source
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.
 */


#include <feral/stdtypes.h>

#include <feral/kern/krnlentry.h>
#include <feral/kern/krnlfirmware.h>

#ifndef _FERAL_KRNL_BASE_H_
#define _FERAL_KRNL_BASE_H_

/* Should complain whenever it's not some multiple of 8 bits. */
typedef struct KrnlPhysicalDisplay
{
	UINT8 BitsPerAlpha;
	UINT8 BitsPerRed;
	UINT8 BitsPerGreen;
	UINT8 BitsPerBlue;

	UINT32 ResolutionX;
	UINT32 ResolutionY;

	VOID *Framebuffer;
} KrnlPhysicalDisplay;

typedef struct KrnlEnvironmentBlock
{
	/* Bootloader should help find free memory areas. */
	STRING CommandLineArgs;
	UINT64 KernelPageSize;
	SystemBootInfo *BootInfo;

	KrnlFirmwareFunctions *FunctionTable;
	KrnlCharMap *CharMap;

	UINT32 PrimaryDisplayIndex;
	UINT32 NumDisplays;
	KrnlPhysicalDisplay *Displays;

	/* Bootloader shouldn't fill these in. */
	STRING KernelVendor;
	UINT8 FeralVersionMajor;
	UINT8 FeralVersionMinor;
	UINT8 FeralVersionPatch;
} KrnlEnvironmentBlock;


VOID KiSystemStartup(KrnlEnvironmentBlock *Block);
VOID KiStartupProcessorMachineDependent(UINT32 Core);

#endif
