/*
Copyright (c) 2018, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining  a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */

// Nothing really here, just so I don't forget to do the most important part of creating Feral.

// (if I had lots of money, we'd probably fork this code for the upcoming Navi architecture too, and get whatever the top-of-the-line model is.)

#ifndef _FERAL_TEAM_RED_ALPHA_LYRAE_GPU_DRIVER_LYRAE_H_
#define _FERAL_TEAM_RED_ALPHA_LYRAE_GPU_DRIVER_LYRAE_H_

#include <feral/stdtypes.h>
#include <feral/feralstatus.h>
#include <ddk/frlddk.h>

FERALSTATUS DriverEntry(HANDLE DeviceHandle, HANDLE RegistryHandle);
FERALSTATUS DriverExit(FERAL_DRIVER Driver);

// TODO: Read documentation and write a driver.

#endif
