/*
Copyright (c) 2018, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */

#ifndef _FERAL_CONSOLE_H_
#define _FERAL_CONSOLE_H_

// We follow POSIX with file IDs, but our names are different...
#define SYS$INPUT  (0)
#define SYS$OUTPUT (1)
#define SYS$ERROR  (2)

// Compatibility...
#define CONIN$ SYS$INPUT
#define CONOUT$ SYS$OUTPUT
#define CONERR$ SYS$ERROR

#ifndef stdin
#define stdin SYS$INPUT
#define stdout SYS$OUTPUT
#define stderr SYS$ERROR
#endif

typedef struct KBRDHANDLE
{
	//TODO...
}KBRDHANDLE;


/**
	Returns a value based upon if the keyboard was recently hit or not.
	If true, then you should read the buffer, otherwise it may be overwritten.

	@return A value denoting if the keyboard was recently hit or not.
 */
BOOL KeyboardHit(KBRDHANDLE* HKeyboard);






#endif
