/*
Copyright (c) 2020 Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute, execute,
and transmit the Software, and to prepare derivative works of the Software,
and to permit third-parties to whom the Software is furnished to do so, all
subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer, must
be included in all copies of the Software, in whole or in part, and all
derivative works of the Software, unless such copies or derivative works are
solely in the form of machine-executable object code generated by a source
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.
 */


#include <arch/x86_64/cpuio.h>
#include <arch/x86_64/cpuinfo.h>
#include <arch/x86_64/cpufuncs.h>

#include <feral/feralstatus.h>
#include <feral/stdtypes.h>
#include <feral/handle.h>
#include <feral/kern/frlos.h>
#include <mm/mm.h>

#include <feral/kern/krnlfuncs.h>
#include <feral/kern/krnlbase.h>

#include <krnl.h>
#include <kern_ver.h>

VOID KiStartupMachineDependent(VOID)
{
	x86InitializeIDT();
}

static GDTPointer GlobalGDT;

VOID x86_install_gdt(GDTPointer *Pointer);

VOID KiStartupProcessorMachineDependent(UINT32 Core)
{
	KiRestoreInterrupts(FALSE);
	if (Core == 0)
	{
		/* setup gdt and idt... */
		UINT16 Limit = 5;
		GDTEntry *Entries = (GDTEntry*)MmKernelMalloc(sizeof(GDTEntry) * Limit);

		/* Set up null descriptor */
		Entries[0].Base = 0;
		Entries[0].High = 0;
		Entries[0].Limit = 0;

		/* Set up kernel code */
		Entries[1].Base = 0;
		Entries[1].High = 0;
		Entries[1].Limit = 0;
		Entries[1].AsBits.SixtyFourMode = 1;
		Entries[1].AsBits.Present = 1;
		Entries[1].AsBits.System = 1;
		Entries[1].AsBits.Executable = 1;
		Entries[1].AsBits.ReadWritable = 1;
		Entries[1].AsBits.Granularity = 1;

		/* Set up kernel data. */
		Entries[2].Base = 0;
		Entries[2].High = 0;
		Entries[2].Limit = 0;
		Entries[2].AsBits.SixtyFourMode = 1;
		Entries[2].AsBits.Present = 1;
		Entries[2].AsBits.System = 1;
		Entries[2].AsBits.ReadWritable = 1;

		/* Set up user code */
		Entries[3].Base = 0;
		Entries[3].High = 0;
		Entries[3].Limit = 0;
		Entries[3].AsBits.SixtyFourMode = 1;
		Entries[3].AsBits.Present = 1;
		Entries[3].AsBits.System = 1;
		Entries[3].AsBits.Executable = 1;
		Entries[3].AsBits.ReadWritable = 1;
		Entries[3].AsBits.Granularity = 1;
		Entries[3].AsBits.PrivLevel = 3;

		/* Set up user data. */
		Entries[4].Base = 0;
		Entries[4].High = 0;
		Entries[4].Limit = 0;
		Entries[4].AsBits.SixtyFourMode = 1;
		Entries[4].AsBits.Present = 1;
		Entries[4].AsBits.System = 1;
		Entries[4].AsBits.ReadWritable = 1;
		Entries[4].AsBits.PrivLevel = 3;

		GlobalGDT.Limit = (sizeof(GDTEntry) * 5) - 1;
		GlobalGDT.Base = (UINT64)(Entries);
		x86_install_gdt(&GlobalGDT);
	}
	KiRestoreInterrupts(TRUE);
}