/*
Copyright (c) 2018, 2019, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute, execute,
and transmit the Software, and to prepare derivative works of the Software,
and to permit third-parties to whom the Software is furnished to do so, all
subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer, must
be included in all copies of the Software, in whole or in part, and all
derivative works of the Software, unless such copies or derivative works are
solely in the form of machine-executable object code generated by a source
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.
 */


#include <feral/stdtypes.h>
#include <arch/x86_64/cpuio.h>
#include <arch/x86_64/cpufuncs.h>


BYTE x86inb(WORD port)
{
	UINT8 RetVal;
	__asm__ volatile("inb %1, %0" : "=a"(RetVal) : "Nd"(port));
	return RetVal;
}

WORD x86inw(WORD port)
{
	UINT16 RetVal;
	__asm__ volatile("inw %1, %0" : "=a"(RetVal) : "Nd"(port));
	return RetVal;
}

DWORD x86inl(WORD port)
{
	UINT32 RetVal;
	__asm__ volatile("inl %1, %0" : "=a"(RetVal) : "Nd"(port));
	return RetVal;
}

VOID x86outb(WORD port, BYTE val)
{
	__asm__ volatile("outb %0, %1" ::"a"(val), "d"(port));
}

VOID x86outw(WORD port, WORD val)
{
	__asm__ volatile("outw %0, %1" ::"a"(val), "d"(port));
}

VOID x86outl(WORD port, DWORD val)
{
	__asm__ volatile("outl %0, %1" ::"a"(val), "d"(port));
}
