/*
Copyright (c) 2018, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining  a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */
 
 #include <feral/stdtypes.h>
#include <feral/port/port.h>


// We get up to 48 characters to define ourselves in a Feral port.
#define PORT_IDENTIFIER				"PHONE Messaging Process"
#define PORT_REQUESTED_NUMBER 		1		/* PHONE gets port 1, in portspace 0. */
#define PORT_REQUESTED_PORTSPACE	0


typedef struct ProgramStatus
{
	UINT64	NumOpenChannels;
}ProgramStatus;

typedef struct Message
{
	FERALTIME TimeSent;
	FERALTIME TimeRead;
	STRING UsernameSender;
	STRING UsernameReciever;
}Message;

typedef struct VoiceMessage
{
	/* TODO */
}VoiceMessage;

typedef struct Channel
{
	/* TODO */
}Channel;

STRING helpMsg = 	"Usage:		\n																												\
					DIAL <username>, when on the same cluster																					\
					DIAL <username>	\\clusterID <ID>, when on a different but interconnected cluster (see A:/System/Hosts for named clusters)		\
					DIAL <username>	\\protocol <ID>/ADDRESS=<ADDRESS>, where ID is \"tcp\", \"renegade\",  or \"decnet\", for a specific protocol 	\
					to be used, and <ADDRESS> is the appropriate address to target.\n\n\n															\
					When a user phones you, the string <NODE>:<USER> is attempting to phone you on <NODE>	[HH:MM:SS|MM:DD:YY]	appears.\n	\
					You can ignore this call, enter the command DIAL REJECT, press CTRL+Z, or, if a GUI is available,									\
					click on the 'Hang Up' icon to stop the call.						\n															\
					If you wish to pick up the call, enter the command DIAL ACCEPT, or click on the \"Accept\" icon if a GUI is present.				\n";

int main(int argc, char** argv)
{
	if (argc < 0)
	{
		
	}

	return 0;
}
