/*
Copyright (c) 2018, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining  a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */

#ifndef _FERAL_DRIVERS_CHROMATIC_
#define _FERAL_DRIVERS_CHROMATIC_

// Defines the global color state.
#include <feral/stdtypes.h>


// RGB for the various peripherals: specific drivers interpret this color accordingly.
static UINT8 Red;
static UINT8 Green;
static UINT8 Blue; 

// We may have some rules set up elsewhere, or the device itself supports it.
// If unsupported, we throw the colors at the device and emulate it in software!
#define RGB_COLORS_STATIC   (0 << 0)	// The color stays the same.
#define RGB_COLORS_BLINKING (1 << 0)	// It blinks. Just as the name says. Stays the color for a bit. Turns off. Repeat.
#define RGB_COLORS_PULSING  (1 << 1)	// It gently goes into the color, then goes off the color.
#define RGB_COLORS_SPECTRUM (1 << 2)	// SHOW ALL THE RGB GLORY!

#endif
