/*
Copyright (c) 2018, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */

#include <stdint.h>

#include <feral/feralstatus.h>
#include <feral/stdtypes.h>

#include <arch/x86_64/vga/vga.h>
#include <arch/x86_64/cpuio.h>

#define VGA_FB_COMMAND_PORT 0x03D4
#define VGA_FB_DATA_PORT    0x03D5

#define VGA_HIGH_BYTE_COMMAND 14
#define VGA_LOW_BYTE_COMMAND  15

volatile DWORD* VGA_LOC = (DWORD*)0xB8000;
static int VGA_CURRENT_LINE = 3;	// so we can leave 3 lines to cpu info

VOID VgaEntry(VgaColorValue foreground, VgaColorValue background, CHAR letter, DWORD posx, DWORD posy)
{
	uint16_t color = ((background << 4) | foreground);
	VGA_LOC[posx + (posy * 40)] = ((uint16_t)letter | (uint16_t) color << 8);
}

VOID KiBlankVgaScreen(DWORD height, DWORD width, DWORD color)
{
	for (DWORD h = 0; h < height; h++)
	{
		for (DWORD w = 0; w < width; w++)
		{
			VGA_LOC[w + (h * 40)] = (uint32_t)color;
		}
	}
}

VOID VgaStringEntry(VgaColorValue foreground, VgaColorValue background, CHAR* string, DWORD length, DWORD posx, DWORD posy)
{
	for (DWORD index = 0; index < length; index++)
	{
		VgaEntry(foreground, background, string[index], posx+index, posy);
	}	
}


VOID VgaPrintln(VgaColorValue foreground, VgaColorValue background, CHAR* string, DWORD length)
{
	if (VGA_CURRENT_LINE == 25)	// This is hardcoded for now, we'll change this later.
	{
		for (int i = 0; i < 25; i++)
		{
			for (int k = 0; k < 40; k++)
			{
				VGA_LOC[k + (i * 40)] = VGA_LOC[k + ((i + 1) * 40)];	//Copy everything over.
			}
		}
		VgaStringEntry(foreground, background, string, length, 0, VGA_CURRENT_LINE - 1);	//Truth be told, I don't completely understand exactly why this works, but OK!
	}
	else
	{
		VgaStringEntry(foreground, background, string, length, 0, VGA_CURRENT_LINE);
		VGA_CURRENT_LINE++;
	}
}

VOID VgaMoveCursor(DWORD PosX, DWORD PosY)
{
	DWORD FinalPos = PosX + (40 * PosY);	//hack, make sure we update length of vga string when we need to.
	x86outb(VGA_FB_COMMAND_PORT, VGA_HIGH_BYTE_COMMAND);
	x86outb(VGA_FB_DATA_PORT, ((FinalPos >> 8) & (0x00FF)));

	x86outb(VGA_FB_COMMAND_PORT, VGA_LOW_BYTE_COMMAND);
	x86outb(VGA_FB_DATA_PORT, ((FinalPos) & (0x00FF)));
}
