/*
Copyright (c) 2018, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */

// Support packeting away objects or something.
// Intent is to share objects to other machines and expose resources (ie, game files).
// We should support distributed computing for the following reasons:
	// - We may need more CPU horsepower to handle something like a game's AI subsytems, or to do physics simulations.
	// - We may need to access a GPU on another system and have it render something (ie, recalculating shadow maps or something)
	// - We need a GPU on another system so as to actually be able to handle very high resolution, where network latency is OK.
	// - We actually have a CPU which can handle a foreign ISA, and thus can accelerate an emulator without actual emulation.

// The primary motivation for this is clustering gaming systems together to utilize all the hardware we can throw at a game (more CPU cores for AI, audio processing, whatever, more GPUs for rendering).
// Horizontal expansion (and reuse of older hardware) is signifigantly cheaper than vertical expansion: you can only get so high clock speeds without resorting to liquid nitrogen,
// and you can only fit so many compute cores on a single graphics card instead of just getting more GPUs. It's less efficient (~187% performace with 2 GPUs, not 200%), but good enough.

// The obvious solution to this is to ask games nicely to use the local GPU for as much as it can while meeting the refresh rate of the local screen,
// then dump all the rest of the work to render off to something else on the network and demand that machine do some of the rendering work (ie, get model info, render to tiles, send tiles back)
// Conceptually not all too different from the first consumer GPU (more of a "general purpose ASIC" or just "coprocessor" than a true dedicated GPU) on a game system for a game released in 1993.

typedef struct 
{
	
}DOB_PACKET;
