/*
Copyright (c) 2020, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */
 
/*  New bootloader. 
 * We'll keep the old one in since this should really be
 * marked as 'staging'. 
 */

/* NOTE: The terms "BIOS", "UEFI" and "firmware" are used INTERCHANGABLY.
 * For the PC-compatible BIOS, "PC-compatible BIOS" is used instead to
 * differentiate between UEFI firmware and PC-compatible BIOS.
 *
 * (For other examples of this convention, see the use of the term "SSL" 
 * to refer to TLS.)
 */

#include <libreefi/efi.h>
#include <feral/stdtypes.h>
#include <feral/feralstatus.h>
#include <feral/kern/krnlbase.h>
#include <feral/kern/krnlentry.h>

#ifndef _FRLBOOT_NO_SUPPORT_ELF64_
#include <drivers/proc/elf/elf.h>

#if defined(__x86_64__)
#define CUR_ARCH_ELF MACHINE_ID_X86_64
#endif
#else
#error "EFI loader not supported for this architecture"
#endif


#define EFI_PAGE_SIZE (4096)
#define EFI_PAGE_SHIFT (12)
#define EFI_PAGE_MAP (~(EFI_PAGE_SIZE - 1))
#define FERAL_VIRT_OFFSET (0xFFFFFFFFC0000000)

/* We need these GUIDs to load the protocols we want. */
static 
EFI_GUID GuidEfiLoadedImageProtocol = EFI_LOADED_IMAGE_PROTOCOL_GUID;

static 
EFI_GUID GuidEfiSimpleFSProtocol = EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_GUID;

static 
EFI_GUID GuidEfiFileInfoGuid = EFI_FILE_INFO_ID;

static 
EFI_GUID GuidEfiGraphicsOutputProtocol = EFI_GRAPHICS_OUTPUT_PROTOCOL_GUID;




/* The EFI table stuff given to us by the firmware. */
static EFI_HANDLE ImageHandle;
static EFI_SYSTEM_TABLE *SystemTable;

/* Firmware function to open stuff. */
static EFI_OPEN_PROTOCOL OpenProtocol;

/* The boot info to give to the kernel... */
static EfiBootInfo *EnvBlock = NULLPTR;


VOID WriteMessage(CHAR16 *String)
{
	SystemTable->ConOut->OutputString(SystemTable->ConOut, String);
}

EFI_STATUS SetupEfiFramebufferData(EFI_HANDLE *VideoBuffers, UINT_PTR *DisplayBuffers)
{
	/* Pointer to the GOP, temporarilly at least. */
	EFI_GRAPHICS_OUTPUT_PROTOCOL *GraphicsProtocol = NULLPTR;
	
	/* Assume at least 1 display */
	for (Iterator = 1; Iterator < NumDisplays; ++Iterator)
	{
		/* Get the current GOP. */
		Result = OpenProtocol(VideoBuffers[Iterator-1],
			&GuidEfiGraphicsOutputProtocol, (VOID **)&GraphicsProtocol,
			ImageHandle, NULL,
			EFI_OPEN_PROTOCOL_BY_HANDLE_PROTOCOL);

		if (Result != EFI_SUCCESS)
		{
			SystemTable->ConOut->OutputString(SystemTable->ConOut,
				L"Failed to query display...\r\n");
			SystemTable->ConOut->OutputString(SystemTable->ConOut,
				EfiErrorToString(Result));
			SystemTable->BootServices->Stall(12500000);
			return Result;
		}

		Result = GraphicsProtocol->SetMode(GraphicsProtocol, PixelRedGreenBlueReserved8BitPerColor);
		if (Result != EFI_SUCCESS)
		{
			SystemTable->ConOut->OutputString(SystemTable->ConOut,
				L"Display does not use 32-bit RGB mode...\r\n");
			SystemTable->ConOut->OutputString(SystemTable->ConOut,
				EfiErrorToString(Result));
			SystemTable->BootServices->Stall(12500000);
			return Result;
		}

		/* Update the current width and height, then display. */
		CurrentWidth = GraphicsProtocol->Mode->Info->HorizontalResolution;
		CurrentHeight = GraphicsProtocol->Mode->Info->VerticalResolution;

		/* And tell the user that we found it! */
		InternalItoaBaseChange(CurrentWidth, ItoaBuf, 10);
		SystemTable->ConOut->OutputString(SystemTable->ConOut,
			L"Got display of width: ");
		SystemTable->ConOut->OutputString(SystemTable->ConOut,
			ItoaBuf);
		SystemTable->ConOut->OutputString(SystemTable->ConOut,
			L" and height of ");
		InternalItoaBaseChange(CurrentHeight, ItoaBuf, 10);
		SystemTable->ConOut->OutputString(SystemTable->ConOut,
			ItoaBuf);
		SystemTable->ConOut->OutputString(SystemTable->ConOut,
			L"\r\n");

		/* HACK: first and second are sizes.*/
		DisplayBuffers[Iterator + 0] = CurrentWidth;
		DisplayBuffers[Iterator + 1] = CurrentHeight;
		DisplayBuffers[Iterator + 2] = GraphicsProtocol->Mode->FrameBufferBase;
	}
}


EFI_STATUS 
EFIAPI uefi_main(EFI_HANDLE mImageHandle, EFI_SYSTEM_TABLE *mSystemTable)
{
	/* Overwrite this variable for status... */
	EFI_STATUS Result = EFI_SUCCESS;

	/* Allow anyone in the bootloader to see these. */
	ImageHandle = mImageHandle;
	SystemTable = mSystemTable;

	UINTN NumDisplays = 0;
	EFI_HANDLE *VideoBuffers = NULLPTR;
	
	/* Get all the GOPs... */
	Result = SystemTable->BootServices->LocateHandleBuffer(ByProtocol,
		&GuidEfiGraphicsOutputProtocol, 
		NULL, 
		&NumDisplays, 
		&VideoBuffers);
		
	OpenProtocol = SystemTable->BootServices->OpenProtocol;
		
	if (Result != EFI_SUCCESS)
	{
		/*  TODO: Handle headless boot. */
		return Result;
	}
	/* Before anything else, get rid of annoying boot splash */
	SystemTable->ConOut->ClearScreen(SystemTable->ConOut);

	WriteMessage(L"Starting Feralboot...\n");
	
	/* Get the locations for the video buffers...
	 * The kernel accepts an "array of structs" style pointer
	 * where the beginning, end, and display data are all defined.
	 */
	UINT_PTR *DisplayBuffers = NULLPTR;
	SystemTable->BootServices->AllocatePool(EfiRuntimeServicesData,
		(sizeof(UINT_PTR) * NumDisplays * 3),
		&DisplayBuffers);
	SetupEfiFramebufferData(VideoBuffers, DisplayBuffers);
	
	
	return EFI_SUCCESS;
}
