/*
Copyright (c) 2020, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */
 
/*  New bootloader. 
 * We'll keep the old one in since this should really be
 * marked as 'staging'. 
 */

/* NOTE: The terms "BIOS", "UEFI" and "firmware" are used INTERCHANGABLY.
 * For the PC-compatible BIOS, "PC-compatible BIOS" is used instead to
 * differentiate between UEFI firmware and PC-compatible BIOS.
 *
 * (For other examples of this convention, see the use of the term "SSL" 
 * to refer to TLS.)
 */

#include <libreefi/efi.h>
#include <feral/stdtypes.h>
#include <feral/feralstatus.h>
#include <feral/kern/krnlbase.h>
#include <feral/kern/krnlentry.h>

#ifndef _FRLBOOT_NO_SUPPORT_ELF64_
#include <drivers/proc/elf/elf.h>

#if defined(__x86_64__)
#define CUR_ARCH_ELF MACHINE_ID_X86_64
#endif
#else
#error "EFI loader not supported for this architecture"
#endif


#define EFI_PAGE_SIZE (4096)
#define EFI_PAGE_SHIFT (12)
#define EFI_PAGE_MAP (~(EFI_PAGE_SIZE - 1))
#define FERAL_VIRT_OFFSET (0xFFFFFFFFC0000000)

/* We need these GUIDs to load the protocols we want. */
static 
EFI_GUID GuidEfiLoadedImageProtocol = EFI_LOADED_IMAGE_PROTOCOL_GUID;

static 
EFI_GUID GuidEfiSimpleFSProtocol = EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_GUID;

static 
EFI_GUID GuidEfiFileInfoGuid = EFI_FILE_INFO_ID;

static 
EFI_GUID GuidEfiGraphicsOutputProtocol = EFI_GRAPHICS_OUTPUT_PROTOCOL_GUID;




/* The EFI table stuff given to us by the firmware. */
static EFI_HANDLE ImageHandle;
static EFI_SYSTEM_TABLE *SystemTable;

/* Firmware function to open stuff. */
static EFI_OPEN_PROTOCOL OpenProtocol;

/* The boot info to give to the kernel... */
static EfiBootInfo *EnvBlock = NULLPTR;


VOID WriteMessage(CHAR16 *String)
{
	SystemTable->ConOut->OutputString(SystemTable->ConOut, String);
}

UINT64 BytesToEfiPages(UINT64 Bytes)
{
	/* Lazy implementation for debugging... */
	UINT64 RetVal = Bytes >> EFI_PAGE_SHIFT;
	if (RetVal % EFI_PAGE_SIZE || RetVal == 0)
	{
		++RetVal;
	}
	return RetVal;
}

/* Borrowed from krnlfuncs... */
VOID InternalItoaBaseChange(UINT64 Val, CHAR16 *Buf, UINT8 Radix)
{
	UINT64 Len = 0;
	UINT64 ValCopy = 0;
	UINT64 ReverseIndex = 0;

	/* No point in continuing if it's zero. Just give '0' back. */
	if (Val == 0)
	{
		*Buf = L'0';
		*(Buf + 1) = L'\0';
		return;
	}
	/* Weird behavior if you exceed 10 + 26 + 26 as radix. */
	for (ValCopy = Val; ValCopy != 0; ValCopy /= Radix)
	{
		/* We need the remainder to see how to encode. */
		CHAR16 Rem = ValCopy % Radix;
		if (Rem <= 9 && Rem >= 0)
		{
			/* It's already a number. Just encode in UTF16. */
			Buf[Len++] = Rem + L'0';
		}
		else if (Rem < 35)
		{
			/* Encode the number as a lowercase letter. */
			Buf[Len++] = (Rem - 10) + L'a';
		}
		else
		{
			/* Encode as uppercase. */
			Buf[Len++] = (Rem - 36) + L'A';
		}
	}

	/* It's written BACKWARDS. So flip the order of the string. */
	for (ReverseIndex = 0; ReverseIndex < Len / 2; ++ReverseIndex)
	{
		CHAR16 Tmp = Buf[ReverseIndex];
		Buf[ReverseIndex] = Buf[Len - ReverseIndex - 1];
		Buf[Len - ReverseIndex - 1] = Tmp;
	}

	/* Terminate the string. */
	Buf[Len] = '\0';
}

BOOL GetEfiMemoryMapToFreeOrNot(EFI_MEMORY_DESCRIPTOR *Place)
{
	switch (Place->Type)
	{
		case EfiLoaderCode:
		case EfiLoaderData:
		case EfiBootServicesCode:
		case EfiBootServicesData:
		case EfiConventionalMemory:
		{
			return TRUE;
		}

		default:
		{
			return FALSE;
		}
	}
}



EFI_STATUS 
EFIAPI uefi_main(EFI_HANDLE mImageHandle, EFI_SYSTEM_TABLE *mSystemTable)
{
	/* Overwrite this variable for status... */
	EFI_STATUS Result = EFI_SUCCESS;

	/* Allow anyone in the bootloader to see these. */
	ImageHandle = mImageHandle;
	SystemTable = mSystemTable;

	UINTN NumDisplays = 0;
	EFI_HANDLE *VideoBuffers = NULLPTR;
	
	/* TODO: Get the ACPI tables from EFI */
	
	
	/* Get all the GOPs... */
	Result = SystemTable->BootServices->LocateHandleBuffer(ByProtocol,
		&GuidEfiGraphicsOutputProtocol, 
		NULL, 
		&NumDisplays, 
		&VideoBuffers);
		
	OpenProtocol = SystemTable->BootServices->OpenProtocol;
		
	if (Result != EFI_SUCCESS)
	{
		/*  TODO: Handle headless boot. */
		return Result;
	}
	/* Before anything else, get rid of annoying boot splash */
	SystemTable->ConOut->ClearScreen(SystemTable->ConOut);

	WriteMessage(L"Starting Feralboot...\n");
	
	/* Get the locations for the video buffers...
	 * The kernel accepts an "array of structs" style pointer
	 * where the beginning, end, and display data are all defined.
	 */
	UINT_PTR *DisplayBuffers = NULLPTR;
	SystemTable->BootServices->AllocatePool(EfiRuntimeServicesData,
		(sizeof(UINT_PTR) * NumDisplays * 3),
		&DisplayBuffers);
	//SetupEfiFramebufferData(VideoBuffers, DisplayBuffers);
	
	
	return EFI_SUCCESS;
}
